version: '3'
services:
  lavalink:
    image: fredboat/lavalink:master
    restart: always
    volumes:
      - ./application.yml:/opt/Lavalink/application.yaml
      - ./lavalink_logs:/opt/Lavalink/logs
    entrypoint: java -Xmx1G -jar Lavalink.jar
  mongodb_container:
    image: mongo:latest
    volumes:
      - mongodb_data_container:/data/db
    restart: always
    logging:
      driver: none
  muusikbot:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep 10; python3.8 bot.py"
    depends_on:
      - mongodb_container
      - lavalink
    links:
      - mongodb_container
      - lavalink

volumes:
  mongodb_data_container:
